### ISSUE TITLE
Can't pass this event to itemsadder api when using the latest version of itemsadder

### ISSUE THREAD

**Issue by kyzzf** [steve4744/WhatIsThis#12]
[09:30:50] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to WhatIsThis v5.7
java.lang.NoClassDefFoundError: dev/lone/itemsadder/api/CustomBlock
	at WhatIsThis-5.7.jar/io.github.steve4744.whatisthis.utils.ItemsAdderHandler.isItemsAdder(ItemsAdderHandler.java:38) ~[?:?]
	at WhatIsThis-5.7.jar/io.github.steve4744.whatisthis.data.DataHandler.isItemsAdderBlock(DataHandler.java:398) ~[?:?]
	at WhatIsThis-5.7.jar/io.github.steve4744.whatisthis.data.DataHandler.getCustomResourceName(DataHandler.java:430) ~[?:?]
	at WhatIsThis-5.7.jar/io.github.steve4744.whatisthis.data.DataHandler.getCustomPrefix(DataHandler.java:458) ~[?:?]
	at WhatIsThis-5.7.jar/io.github.steve4744.whatisthis.data.DataHandler.processBlock(DataHandler.java:262) ~[?:?]
	at WhatIsThis-5.7.jar/io.github.steve4744.whatisthis.listeners.PlayerMoveListener.onPlayerMove(PlayerMoveListener.java:56) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1246.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-122-4430e96]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1561) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:34) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.handle(ServerboundMovePlayerPacket.java:105) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1471) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1316) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassNotFoundException: dev.lone.itemsadder.api.CustomBlock
	... 31 more

**Comment by kyzzf** [comment]
NVM it was just my itemsadder that was disabled, sorry
