### ISSUE TITLE
[19:12:41 ERROR]: Could not pass event PlayerMoveEvent to WhatIsThis v5.1

### ISSUE THREAD

**Issue by AE720** [steve4744/WhatIsThis#8]
This error floods the console whenever a player uses a boat. Even adding the boat itself to the blacklist doesn't prevent the error from happening.

[19:12:41 ERROR]: Could not pass event PlayerMoveEvent to WhatIsThis v5.1
java.lang.NoSuchMethodError: 'org.bukkit.entity.Boat$Type org.bukkit.entity.Boat.getBoatType()'
	at io.github.steve4744.whatisthis.data.DataHandler.getVariant(DataHandler.java:467) ~[WhatIsThis-5.1.jar:?]
	at io.github.steve4744.whatisthis.data.DataHandler.getEntityDisplayName(DataHandler.java:173) ~[WhatIsThis-5.1.jar:?]
	at io.github.steve4744.whatisthis.data.DataHandler.processEntity(DataHandler.java:207) ~[WhatIsThis-5.1.jar:?]
	at io.github.steve4744.whatisthis.listeners.PlayerMoveListener.onPlayerMove(PlayerMoveListener.java:61) ~[WhatIsThis-5.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor484.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-388]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1505) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:66) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1504) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by steve4744** [comment]
Thanks for letting me know. The `getBoatType` method was added in 1.19 which is why you have the error in 1.18. I'll fix that in the next update.

Did you add BOAT to the blacklisted blocks or entities? If you add it to the list of ignored entities in the config it should stop the console errors:
```
IgnoreEntities:
- COW
- BOAT
```

**Comment by AE720** [comment]
Thank you immensely for the prompt and helpful response. You are correct, I had it in blocks. Thanks for letting me know the proper syntax too (BOAT, instead of X_BOAT).

**Comment by steve4744** [comment]
This is fixed in the 5.2-SNAPSHOT.
